# Generated by MEX → Python/TensorFlow
# MEX is a learning language for ML
# This converts your MEX code to production Python

import tensorflow as tf
import numpy as np

# Data: 3 points
xs = np.array([1, 2, 3]).reshape(-1, 1)
ys = np.array([2, 4, 6]).reshape(-1, 1)


# Run the model
if __name__ == "__main__":
    # Compile the model
    model.compile(optimizer='sgd', loss='mse')

    # Train the model
    model.fit(xs, ys, epochs=EPOCHS, verbose=0)

    # Make a sample prediction
    # prediction = model.predict(np.array([[5]]))
    # print(f"Prediction: {prediction.numpy()[0][0]:.4f}")