// ═══════════════════════════════════════════════════════
//  MEX CODE GENERATOR — Converts AST to TensorFlow.js
// ═══════════════════════════════════════════════════════

function generate(ast) {
  const output = [];
  let indent = 0;

  function line(code) {
    output.push('  '.repeat(indent) + code);
  }

  function generateNode(node) {
    switch (node.type) {
      case 'Program': return generateProgram(node);
      case 'DataPoints': return generateDataPoints(node);
      case 'DataCSV': return generateDataCSV(node);
      case 'ModelDecl': return generateModelDecl(node);
      case 'TrainSection': return generateTrain(node);
      case 'PredictSection': return generatePredict(node);
      case 'ShowSection': return generateShow(node);
      case 'Let': return generateLet(node);
      case 'Assignment': return generateAssignment(node);
      case 'If': return generateIf(node);
      case 'For': return generateFor(node);
      case 'While': return generateWhile(node);
      case 'Function': return generateFunction(node);
      case 'Return': return generateReturn(node);
      case 'Print': return generatePrint(node);
      case 'Import': return generateImport(node);
      case 'Export': return generateExport(node);
      case 'PredictExpr': return generatePredictExpr(node);
      case 'BinaryOp': return generateBinaryOp(node);
      case 'UnaryOp': return generateUnaryOp(node);
      case 'Identifier': return node.name;
      case 'Number': return String(node.value);
      case 'String': return `"${node.value}"`;
      case 'Boolean': return node.value ? 'true' : 'false';
      case 'Call': return generateCall(node);
      default:
        throw new Error(`Unknown node type: ${node.type}`);
    }
  }

  // ── Program ──────────────────────────────────────
  function generateProgram(node) {
    line('// Generated by MEX → TensorFlow.js');
    line('const tf = require("@tensorflow/tfjs-node");');
    line('');
    for (const stmt of node.body) {
      generateNode(stmt);
      line('');
    }
    return output.join('\n');
  }

  // ── Data Points ──────────────────────────────────
  function generateDataPoints(node) {
    const xs = node.points.map(p => p[0]);
    const ys = node.points.map(p => p[1]);
    line(`// Data: ${node.points.length} points`);
    line(`const xs = tf.tensor1d([${xs.join(', ')}]);`);
    line(`const ys = tf.tensor1d([${ys.join(', ')}]);`);
  }

  // ── Data CSV ─────────────────────────────────────
  function generateDataCSV(node) {
    line(`// Load data from ${node.filename}`);
    line(`const data = require("./${node.filename}");`);
    line('const xs = tf.tensor2d(data.inputs);');
    line('const ys = tf.tensor2d(data.outputs);');
  }

  // ── Model Declaration ────────────────────────────
  function generateModelDecl(node) {
    if (node.modelType === 'simple') {
      line('// Simple linear model');
      line('const model = tf.sequential();');
      line('model.add(tf.layers.dense({ units: 1, inputShape: [1] }));');
    } else if (node.modelType === 'sequential') {
      line('// Sequential model');
      line('const model = tf.sequential();');
      for (const layer of node.layers) {
        if (layer.type === 'DenseLayer') {
          line(`model.add(tf.layers.dense({ units: ${layer.units}, activation: "${layer.activation}" }));`);
        } else if (layer.type === 'DropoutLayer') {
          line(`model.add(tf.layers.dropout({ rate: ${layer.rate} }));`);
        }
      }
    }
  }

  // ── Training ─────────────────────────────────────
  function generateTrain(node) {
    const optimizer = node.optimizer || 'adam';
    const loss = node.loss || 'meanSquaredError';
    line(`// Train for ${node.epochs} epochs`);
    line(`model.compile({ optimizer: "${optimizer}", loss: "${loss}" });`);
    line(`await model.fit(xs, ys, { epochs: ${node.epochs} });`);
  }

  // ── Prediction ───────────────────────────────────
  function generatePredict(node) {
    const input = node.input.type === 'Number' ? node.input.value : node.input;
    line(`// Predict for ${input}`);
    line(`const prediction = model.predict(tf.tensor1d([${input}]));`);
    line('prediction.print();');
  }

  // ── Show ─────────────────────────────────────────
  function generateShow(node) {
    switch (node.what) {
      case 'data':
        line('console.log("Data loaded");');
        break;
      case 'model':
        line('model.summary();');
        break;
      case 'accuracy':
        line('console.log("Training complete");');
        break;
      case 'loss':
        line('console.log("Loss:", model.loss);');
        break;
      case 'results':
        line('console.log("Results available");');
        break;
    }
  }

  // ── Let ──────────────────────────────────────────
  function generateLet(node) {
    const value = generateNode(node.value);
    line(`let ${node.name} = ${value};`);
  }

  // ── Assignment ───────────────────────────────────
  function generateAssignment(node) {
    const value = generateNode(node.value);
    line(`${node.name} = ${value};`);
  }

  // ── If/Else ──────────────────────────────────────
  function generateIf(node) {
    const condition = generateNode(node.condition);
    line(`if (${condition}) {`);
    indent++;
    for (const stmt of node.body) {
      generateNode(stmt);
    }
    indent--;
    if (node.elseBody) {
      line('} else {');
      indent++;
      if (Array.isArray(node.elseBody)) {
        for (const stmt of node.elseBody) {
          generateNode(stmt);
        }
      } else {
        generateNode(node.elseBody);
      }
      indent--;
    }
    line('}');
  }

  // ── For Loop ─────────────────────────────────────
  function generateFor(node) {
    line(`for (let ${node.varName} = ${node.start}; ${node.varName} < ${node.end}; ${node.varName}++) {`);
    indent++;
    for (const stmt of node.body) {
      generateNode(stmt);
    }
    indent--;
    line('}');
  }

  // ── While Loop ───────────────────────────────────
  function generateWhile(node) {
    const condition = generateNode(node.condition);
    line(`while (${condition}) {`);
    indent++;
    for (const stmt of node.body) {
      generateNode(stmt);
    }
    indent--;
    line('}');
  }

  // ── Function ─────────────────────────────────────
  function generateFunction(node) {
    line(`function ${node.name}(${node.params.join(', ')}) {`);
    indent++;
    for (const stmt of node.body) {
      generateNode(stmt);
    }
    indent--;
    line('}');
  }

  // ── Return ───────────────────────────────────────
  function generateReturn(node) {
    const value = node.value ? generateNode(node.value) : '';
    line(`return ${value};`);
  }

  // ── Print ────────────────────────────────────────
  function generatePrint(node) {
    const args = node.args.map(arg => generateNode(arg)).join(', ');
    line(`console.log(${args});`);
  }

  // ── Import ───────────────────────────────────────
  function generateImport(node) {
    if (node.names) {
      const names = node.names.map(n => n.alias || n.name).join(', ');
      line(`const { ${names} } = require("./${node.path.replace('.mx', '.js')}");`);
    } else {
      line(`const module = require("./${node.path.replace('.mx', '.js')}");`);
    }
  }

  // ── Export ───────────────────────────────────────
  function generateExport(node) {
    if (node.names) {
      line(`module.exports = { ${node.names.join(', ')} };`);
    }
    if (node.declarations) {
      for (const decl of node.declarations) {
        generateNode(decl);
      }
    }
  }

  // ── Predict Expression ───────────────────────────
  function generatePredictExpr(node) {
    const input = generateNode(node.input);
    return `model.predict(tf.tensor1d([${input}])).dataSync()[0]`;
  }

  // ── Binary Operation ─────────────────────────────
  function generateBinaryOp(node) {
    const left = generateNode(node.left);
    const right = generateNode(node.right);
    const opMap = {
      'PLUS': '+',
      'MINUS': '-',
      'STAR': '*',
      'SLASH': '/',
      'PERCENT': '%',
      'EQEQ': '===',
      'NEQ': '!==',
      'LT': '<',
      'GT': '>',
      'LTE': '<=',
      'GTE': '>=',
      'AND': '&&',
      'OR': '||',
    };
    return `(${left} ${opMap[node.op]} ${right})`;
  }

  // ── Unary Operation ──────────────────────────────
  function generateUnaryOp(node) {
    const expr = generateNode(node.expr);
    if (node.op === 'MINUS') return `(-${expr})`;
    if (node.op === 'NOT') return `(!${expr})`;
    return expr;
  }

  // ── Function Call ────────────────────────────────
  function generateCall(node) {
    const args = node.args.map(arg => generateNode(arg)).join(', ');
    return `${node.name}(${args})`;
  }

  return generateNode(ast);
}

module.exports = { generate };
